pipeline {
    agent any

    tools {
        maven "M3"
    }

    stages {
        stage('Build') {
            steps {
                git 'https://github.com/christianeduardoarosreuss/kibernumfinal.git'

                sh "mvn -Dmaven.test.failure.ignore=true clean package"

            }

        }
    stage('testing') {
            steps {

                sh "mvn test"

            }

        }
    }
   
}
